name: Bug report
description: Create a report to help us improve
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Enter a detailed description of the bug"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Reproducible Code"
      description: "Provide code or steps needed to reproduce the bug."
      placeholder: "Enter code snippet or reproduction steps"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Environment"
      description: "Provide details such as OS, version, etc."
      placeholder: "OS: \nVersion: "
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Enter what you expected to happen"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Screenshots"
      description: "Add screenshots to help explain your problem."
      placeholder: "Provide screenshot links or instructions to attach images"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
      placeholder: "Enter any additional context"
    validations:
      required: false
