name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "images/**"
      - "**.md"
      - "**.yml"
      - "LICENSE-**"
      - ".gitmessage"
      - ".pre-commit-config.yaml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "images/**"
      - "**.md"
      - "**.yml"
      - "LICENSE-**"
      - ".pre-commit-config.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  package-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install
      run: |
        rustup update stable
        cargo install --path .
    - name: boto3
      run: |
        pip3 install boto3
        pylyzer -c "import boto3"
        echo "OK: boto3"
    - name: urllib3
      run: |
        pip3 install urllib3
        pylyzer -c "import urllib3"
        echo "OK: urllib3"
    - name: setuptools
      run: |
        pip3 install setuptools
        pylyzer -c "import setuptools"
        echo "OK: setuptools"
    - name: requests
      run: |
        pip3 install requests
        pylyzer -c "import requests"
        echo "OK: requests"
    - name: certifi
      run: |
        pip3 install certifi
        pylyzer -c "import certifi"
        echo "OK: certifi"
    - name: charset-normalizer
      run: |
        pip3 install charset-normalizer
        pylyzer -c "import charset_normalizer"
        echo "OK: charset-normalizer"
    - name: idna
      run: |
        pip3 install idna
        pylyzer -c "import idna"
        echo "OK: idna"
